## HW4題目
> 請參考上課所講的 MyMinMaxScaler 的範例，參考StandardScaler仿寫一個 MyStandardScaler。

### 先使用sklearn測試

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [3]:
scaler = StandardScaler()

In [5]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
scaler.mean_

array([ 0.5,  0.5])

In [7]:
scaler.var_

array([ 0.25,  0.25])

In [8]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [9]:
scaler.transform([[1,2]])

array([[ 1.,  3.]])

### 使用自己的Standard Scaler

In [10]:
import numpy as np

In [11]:
np.mean(data, axis=0)

array([ 0.5,  0.5])

In [12]:
np.var(data, axis=0)

array([ 0.25,  0.25])

In [13]:
(np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [14]:
class MyStandardScaler: 
    
    def __init__(self):                            
        self.mean = None
        self.var = None
        
    def fit(self,data):                           
        self.mean = np.mean(data, axis=0)
        self.var  = np.var(data, axis=0)
        
    def transform(self,data):
        return (np.array(data) - scaler.mean_ ) / (scaler.var_**0.5)
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

### 測試自己的結果是否與套件一致

In [15]:
myscaler = MyStandardScaler()

In [16]:
myscaler.fit(data)

In [17]:
myscaler.mean

array([ 0.5,  0.5])

In [18]:
myscaler.var

array([ 0.25,  0.25])

In [19]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [20]:
myscaler.transform([[1,2]])

array([[ 1.,  3.]])